


























































































100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 68124/68124 [03:04<00:00, 368.90it/s]





























100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 22631/22631 [00:58<00:00, 385.05it/s]


















100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 15509/15509 [00:39<00:00, 393.51it/s]











100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 10844/10844 [00:23<00:00, 466.12it/s]
Traceback (most recent call last):
  File "train_tacred.py", line 276, in <module>
    main()
  File "train_tacred.py", line 271, in main
    train_token(args, model, train_features, benchmarks)
  File "train_tacred.py", line 96, in train_token
    train_dataloader = DataLoader(train_features, batch_size=args.train_batch_size, shuffle=True, collate_fn=collate_fn_token, drop_last=True)
NameError: name 'collate_fn_token' is not defined
Traceback (most recent call last):
  File "train_tacred.py", line 276, in <module>
    main()
  File "train_tacred.py", line 271, in main
    train_token(args, model, train_features, benchmarks)
  File "train_tacred.py", line 96, in train_token
    train_dataloader = DataLoader(train_features, batch_size=args.train_batch_size, shuffle=True, collate_fn=collate_fn_token, drop_last=True)
NameError: name 'collate_fn_token' is not defined