
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 404.59it/s]

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 405.24it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 413.46it/s]
 39%|████████████████████████████████████████████████▌                                                                           | 392/1000 [00:00<00:01, 375.73it/s]
Total steps: 1250
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:02<00:00, 454.64it/s]
  0%|                                                                                                                                        | 0/250 [00:00<?, ?it/s]/usr/local/lib/python3.6/dist-packages/transformers-2.3.0-py3.6.egg/transformers/optimization.py:146: UserWarning: This overload of add_ is deprecated:
	add_(Number alpha, Tensor other)
Consider using one of the following signatures instead:
	add_(Tensor other, *, Number alpha) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:1050.)
  exp_avg.mul_(beta1).add_(1.0 - beta1, grad)









100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 250/250 [00:19<00:00, 13.11it/s]









 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 248/250 [00:19<00:00, 12.80it/s]
{'dev_f1': 49.32249322493225}
{'test_f1': 54.33526011560694}
 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 248/250 [00:19<00:00, 12.80it/s]Traceback (most recent call last):
  File "train_retacred.py", line 255, in <module>
    main()
  File "train_retacred.py", line 251, in main
    train(args, model, train_features, benchmarks)
  File "train_retacred.py", line 59, in train
    f1, output = evaluate(args, model, features, tag=tag)
  File "train_retacred.py", line 162, in evaluate
    accuracy_challenge(keys, preds)
  File "/nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/evaluation.py", line 60, in accuracy_challenge
    with open("dataset/challenge_set.json", "r") as tacred_test_file:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/challenge_set.json'
Traceback (most recent call last):
  File "train_retacred.py", line 255, in <module>
    main()
  File "train_retacred.py", line 251, in main
    train(args, model, train_features, benchmarks)
  File "train_retacred.py", line 59, in train
    f1, output = evaluate(args, model, features, tag=tag)
  File "train_retacred.py", line 162, in evaluate
    accuracy_challenge(keys, preds)
  File "/nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/evaluation.py", line 60, in accuracy_challenge
    with open("dataset/challenge_set.json", "r") as tacred_test_file:
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/challenge_set.json'
 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 248/250 [00:28<00:00,  8.61it/s]