2022-03-13 19:18:19,290 INFO    MainThread:16226 [wandb_setup.py:_flush():75] Loading settings from /nethome/mrungta8/.config/wandb/settings
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_setup.py:_flush():75] Loading settings from /nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/meta_learning/wandb/settings
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'Mukund/RE_improved_baseline/meta_learning/train_tacred.py', 'program': 'train_tacred.py'}
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_init.py:_log_setup():386] Logging user logs to /nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/meta_learning/wandb/run-20220313_191819-3a7jk5k8/logs/debug.log
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_init.py:_log_setup():387] Logging internal logs to /nethome/mrungta8/project/ProjectPURE/Mukund/RE_improved_baseline/meta_learning/wandb/run-20220313_191819-3a7jk5k8/logs/debug-internal.log
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_init.py:init():420] calling init triggers
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {}
2022-03-13 19:18:19,291 INFO    MainThread:16226 [wandb_init.py:init():471] starting backend
2022-03-13 19:18:19,291 INFO    MainThread:16226 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-13 19:18:19,304 INFO    MainThread:16226 [backend.py:ensure_launched():219] starting backend process...
2022-03-13 19:18:19,314 INFO    MainThread:16226 [backend.py:ensure_launched():225] started backend process with pid: 16376
2022-03-13 19:18:19,315 INFO    MainThread:16226 [wandb_init.py:init():480] backend started and connected
2022-03-13 19:18:19,324 INFO    MainThread:16226 [wandb_init.py:init():550] updated telemetry
2022-03-13 19:18:19,351 INFO    MainThread:16226 [wandb_init.py:init():581] communicating current version
2022-03-13 19:18:20,385 INFO    MainThread:16226 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.12.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-03-13 19:18:20,386 INFO    MainThread:16226 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-13 19:18:20,485 INFO    MainThread:16226 [wandb_init.py:init():624] starting run threads in backend
2022-03-13 19:18:22,221 INFO    MainThread:16226 [wandb_run.py:_console_start():1827] atexit reg
2022-03-13 19:18:22,222 INFO    MainThread:16226 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.REDIRECT
2022-03-13 19:18:22,224 INFO    MainThread:16226 [wandb_run.py:_redirect():1706] Redirecting console.
2022-03-13 19:18:22,226 INFO    MainThread:16226 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-13 19:18:22,226 INFO    MainThread:16226 [wandb_init.py:init():651] run started, returning control to user process
2022-03-13 19:18:34,353 INFO    MainThread:16226 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-03-13 19:18:34,355 INFO    MainThread:16226 [wandb_run.py:_restore():1769] restore
2022-03-13 19:18:36,745 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 949
  total_bytes: 949
}

2022-03-13 19:18:37,001 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 949
  total_bytes: 949
}

2022-03-13 19:18:37,544 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 949
  total_bytes: 6766
}

2022-03-13 19:18:37,648 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4952
  total_bytes: 6766
}

2022-03-13 19:18:37,751 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6766
  total_bytes: 6766
}

2022-03-13 19:18:37,854 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6766
  total_bytes: 6766
}

2022-03-13 19:18:37,958 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6766
  total_bytes: 6766
}

2022-03-13 19:18:38,061 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6766
  total_bytes: 6766
}

2022-03-13 19:18:38,288 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6766
  total_bytes: 6766
}

2022-03-13 19:18:38,509 INFO    MainThread:16226 [wandb_run.py:_wait_for_finish():1929] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6766
  total_bytes: 6766
}
local_info {
}

2022-03-13 19:18:39,994 INFO    MainThread:16226 [wandb_run.py:_append_files():2194] logging synced files
